version: '3'
services:
  site:
    depends_on:
      - db
    volumes:
      - ../:/var/www/html/
      -  ./webconfig:/etc/apache2/sites-enabled
      - ../tmp:/tmp
    build: .
    container_name: site
    ports:
      - 80:80
      - 443:443
    links:
      - db
    environment: #закоммнетировать для vps
      XDEBUG_CONFIG: ${XDEBUG_CONFIG} #закоммнетировать для vps
      UPLOAD_LIMIT: 64M #закоммнетировать для vps
    restart: always
  db:
    image: mysql:8.0.21
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sort_buffer_size=512K
    ports:
      - 3306:3306
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: platform
      MYSQL_ROOT_PASSWORD: 123