version: '3'
services:
  site:
    depends_on:
      - db
      - memcached
    volumes:
      - ../:/var/www/html/
      -  ./webconfig:/etc/apache2/sites-enabled
      - ../tmp:/tmp
    build: .
    container_name: site
    ports:
      - 80:80
    links:
      - db
#    environment: #разкоммнетировать для local от
#      XDEBUG_CONFIG: ${XDEBUG_CONFIG} #разкоммнетировать для vps от
#      UPLOAD_LIMIT: 64M #разкоммнетировать для vps до
    restart: always
  db:
    image: mysql:8.0.21
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sort_buffer_size=512K
    ports:
      - 3306:3306
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: NtEd5!31_o5NY4X
      MYSQL_DATABASE: platform
      MYSQL_ROOT_PASSWORD: NtEd5!31_o5NY4X

  memcached:
    image: memcached:latest
    restart: always
    container_name: memcached
    ports:
      - "11211:11211"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - 9090:80
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=NtEd5!31_o5NY4X